import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { GRID_SIZE, pinOffsets } from "@/lib/circuit/geometry";
import type { NodeDefinition, ParamSpec } from "@/lib/nodes/define";
import { nodeCategories, nodeDefinitions } from "@/lib/nodes/registry";

/**
 * Writes one Markdown file per registered node type, plus an index, from the
 * live definitions in `src/lib/nodes/`. Run through `gen-node-docs.sh`.
 *
 * Imported rather than scraped: `docs` strings are assembled from shared
 * suffixes (every gate appends `SHARED_GATE_DOCS`), and pins and footprints
 * are functions of params that `defineNode` may widen to fit a title. Only
 * running the definition gives the numbers the canvas actually uses.
 */

const outDir = process.argv[2];
if (!outDir) {
  console.error("usage: node-docs.ts <out-dir>");
  process.exit(2);
}
mkdirSync(outDir, { recursive: true });

const categoryLabel = new Map(nodeCategories.map((c) => [c.id, c.label]));

const fileName = (type: string) => `${type}.md`;

/** The "On the canvas" sections describe mouse gestures; an agent writes JSON. */
function stripCanvasSections(markdown: string): string {
  return markdown
    .trim()
    .replace(/\n## On the canvas\n[\s\S]*?(?=\n## |\s*$)/g, "")
    .trim();
}

function firstSentence(markdown: string | undefined): string {
  const paragraph = (markdown ?? "").trim().split(/\n\s*\n/)[0] ?? "";
  const flat = paragraph.replace(/\s+/g, " ").trim();
  const end = flat.search(/[.:](\s|$)/);
  return (end > 0 ? flat.slice(0, end + 1) : flat).replace(/\|/g, "\\|");
}

function cell(value: unknown): string {
  if (value === undefined) return "";
  const text = typeof value === "string" ? value : JSON.stringify(value);
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function paramRange(spec: ParamSpec): string {
  switch (spec.kind) {
    case "int": {
      const parts = [
        spec.min !== undefined ? `min ${spec.min}` : "",
        spec.max !== undefined ? `max ${spec.max}` : "",
      ].filter(Boolean);
      return parts.join(", ");
    }
    case "bool":
      return "`true` / `false`";
    case "text":
      return [
        spec.maxLength ? `≤ ${spec.maxLength} chars` : "",
        spec.multiline ? "multiline" : "",
      ]
        .filter(Boolean)
        .join(", ");
    case "select":
    case "color":
      return spec.options.map((o) => `\`${o.value}\``).join(", ");
  }
}

function render(def: NodeDefinition): string {
  const params = def.defaultParams;
  const size = def.size(params);
  const pins = def.pins(params);
  const offsets = pinOffsets(pins, size, 0);
  const lines: string[] = [];

  lines.push(`# ${def.title} — \`${def.type}\``, "");
  lines.push(
    "<!-- Generated by scripts/gen-node-docs.sh from src/lib/nodes/. Do not edit. -->",
    "",
  );

  const facts = [
    [
      "Category",
      `${categoryLabel.get(def.category) ?? def.category} (\`${def.category}\`)`,
    ],
    ["Canvas name", def.shortTitle ?? def.title],
    ["Pin names drawn", def.kind === "basic" ? "no (basic)" : "yes (compound)"],
    [
      "Footprint (default params)",
      `${size.width} × ${size.height} cells = ${size.width * GRID_SIZE} × ${size.height * GRID_SIZE} world units`,
    ],
  ];
  if (def.decoration) {
    facts.push([
      "Decoration",
      def.decoration.enclosure
        ? "yes — enclosure, painted under wires; no pins, not simulated"
        : "yes — painted above wires; no pins, not simulated",
    ]);
  }
  if (def.resize) {
    facts.push([
      "Resizable",
      `\`${def.resize.width.key}\` ${def.resize.width.min}–${def.resize.width.max}, \`${def.resize.height.key}\` ${def.resize.height.min}–${def.resize.height.max} (cells)`,
    ]);
  }
  if (def.group) {
    facts.push([
      "Grouped by",
      `nodes sharing \`params.${def.group.key}\` form one ${def.group.noun}${def.group.shared?.length ? `; shared: ${def.group.shared.map((s) => `\`${s}\``).join(", ")}` : ""}`,
    ]);
  }
  if (def.netAliases) {
    facts.push([
      "Net join",
      "same-named instances are one net, no wire needed",
    ]);
  }
  if (def.delayNs) facts.push(["Delay", `${def.delayNs(params)} ns`]);
  lines.push("| | |", "| --- | --- |");
  for (const [key, value] of facts) lines.push(`| ${key} | ${value} |`);
  lines.push("");

  lines.push("## Node JSON", "");
  lines.push("```json");
  lines.push(
    JSON.stringify(
      {
        id: `n_${def.type.split(".").pop()}1`,
        type: def.type,
        position: { x: 0, y: 0 },
        params,
      },
      null,
      2,
    ),
  );
  lines.push("```", "");

  if (def.paramsSchema?.length) {
    lines.push("## Params", "");
    lines.push("| Key | Label | Kind | Allowed | Default | Hint |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const spec of def.paramsSchema) {
      lines.push(
        `| \`${spec.key}\` | ${cell(spec.label)} | ${spec.kind} | ${cell(paramRange(spec))} | \`${cell(params[spec.key])}\` | ${cell(spec.hint)} |`,
      );
    }
    const listed = new Set(def.paramsSchema.map((spec) => spec.key));
    const unlisted = Object.keys(params).filter((key) => !listed.has(key));
    if (unlisted.length) {
      lines.push(
        "",
        `Also in \`defaultParams\` with no editor: ${unlisted.map((k) => `\`${k}\``).join(", ")}.`,
      );
    }
    lines.push("");
  }

  lines.push("## Pins (default params, rotation 0)", "");
  if (offsets.length === 0) {
    lines.push("None.", "");
  } else {
    lines.push(
      "`dx, dy` are world units from the node's `position` (its top-left). Pin ids go in wire `from`/`to`.",
      "",
    );
    lines.push("| Pin id | Name | Dir | Width | Side | dx, dy |");
    lines.push("| --- | --- | --- | --- | --- | --- |");
    for (const o of offsets) {
      lines.push(
        `| \`${o.spec.id}\` | ${cell(o.spec.name)} | ${o.spec.direction}${o.spec.tristate ? " (tri-state)" : ""} | ${o.spec.width} | ${o.side} | ${o.dx}, ${o.dy} |`,
      );
    }
    lines.push(
      "",
      "Pins, widths and footprint change with params and rotation. For anything but the defaults run:",
      "",
      "```bash",
      `bun .claude/skills/logits-circuit/scripts/pins.ts ${def.type} '${JSON.stringify(params).replace(/'/g, "'\\''")}' 0`,
      "```",
      "",
    );
  }

  if (def.docs) {
    lines.push("## Behaviour", "");
    // Demote the node's own headings one level under this page's `##`.
    lines.push(stripCanvasSections(def.docs).replace(/^(#+) /gm, "#$1 "), "");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

const byCategory = new Map<string, NodeDefinition[]>();
for (const def of nodeDefinitions) {
  writeFileSync(join(outDir, fileName(def.type)), render(def));
  const list = byCategory.get(def.category) ?? [];
  list.push(def);
  byCategory.set(def.category, list);
}

const index: string[] = [
  "# Node reference",
  "",
  "<!-- Generated by scripts/gen-node-docs.sh from src/lib/nodes/. Do not edit. -->",
  "",
  `${nodeDefinitions.length} node types, in palette order. Open a file only for the types you are placing.`,
  "",
];
const order = [
  ...nodeCategories.map((c) => c.id),
  ...[...byCategory.keys()].filter((id) => !categoryLabel.has(id)),
];
for (const id of order) {
  const defs = byCategory.get(id);
  if (!defs) continue;
  index.push(`## ${categoryLabel.get(id) ?? id}`, "");
  index.push("| Type | Title | What it is |", "| --- | --- | --- |");
  for (const def of defs) {
    index.push(
      `| [\`${def.type}\`](${fileName(def.type)}) | ${cell(def.title)} | ${firstSentence(def.docs)} |`,
    );
  }
  index.push("");
}
writeFileSync(join(outDir, "README.md"), `${index.join("\n").trimEnd()}\n`);

console.log(
  `wrote ${nodeDefinitions.length} node docs + README.md to ${outDir}`,
);
