import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BaseProvider from "@/components/providers/base";
import {
  USER_SETTINGS_COOKIE_NAME,
  retrieveUserSettingsFromCookieValue,
} from "@/data/settings-cookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialSettings = retrieveUserSettingsFromCookieValue(
    cookieStore.get(USER_SETTINGS_COOKIE_NAME)?.value,
  );
  const themeClass = initialSettings.appearance?.theme === "dark" ? "dark" : "";

  return (
    <html lang="en" className={themeClass} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-geist antialiased`}
      >
        <BaseProvider initialSettings={initialSettings}>{children}</BaseProvider>
      </body>
    </html>
  );
}
