import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BaseProvider from "@/components/providers/base";
import {
  RESOLVED_SYSTEM_THEME_COOKIE_NAME,
  USER_SETTINGS_COOKIE_NAME,
  retrieveResolvedSystemThemeFromCookieValue,
  retrieveUserSettingsFromCookieValue,
} from "@/data/settings-cookie";
import { getColorSchemeClassName } from "@/coloe-scheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const initialSettings = retrieveUserSettingsFromCookieValue(
    cookieStore.get(USER_SETTINGS_COOKIE_NAME)?.value,
  );
  const resolvedSystemTheme = retrieveResolvedSystemThemeFromCookieValue(
    cookieStore.get(RESOLVED_SYSTEM_THEME_COOKIE_NAME)?.value,
  );
  const configuredTheme = initialSettings.appearance?.theme ?? "system";
  const effectiveTheme =
    configuredTheme === "system" ? resolvedSystemTheme ?? "light" : configuredTheme;
  const isDark = effectiveTheme === "dark";
  const initialColorSchemeClass = getColorSchemeClassName(
    initialSettings.appearance?.colorScheme,
    isDark ? "dark" : "light",
  );
  const rootClassName = [isDark ? "dark" : "", initialColorSchemeClass]
    .filter(Boolean)
    .join(" ");

  return (
    <html lang="en" className={rootClassName} suppressHydrationWarning>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, interactive-widget=resizes-content"
        ></meta>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} font-geist antialiased`}
      >
        <BaseProvider initialSettings={initialSettings}>
          {children}
        </BaseProvider>
      </body>
    </html>
  );
}
